[theme]
primaryColor = "#00A896"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F8FB"
textColor = "#1C2B4B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
